#!/bin/bash
su betty

[A[A[C[C[C[C[C[C[C[C
wc-1 0-iam_betty
2 0-iam_betty
chmod u+x 0-iam_betty
ls
[A[C[A[A[A[A[A[A[A[A[B[B[C[C[C[C[C[[[[C>  [C[C-[D0
[B[B[B[B[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C
clear
[A[C[[A[C[C[C[C[C[C[C[C[A[C[C[C[C[C[C[A[C[C[C[C[A[C[C[C[[A[C[C[C[C[C[[A[C[C[C[C[C[C[C[C[C[C[clear
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[D[D[D[D[D[D[D[D[[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[in)
git push
